use base64::Engine;
use hmac::{Hmac, Mac};
use rand::RngCore;
use sha1::Sha1;

/// Format: `|1|base64(salt)|base64(HMAC-SHA1(salt, hostname))`
/// Salt is 20 bytes (SHA1 digest length), matching OpenSSH's
/// `ssh_hmac_bytes(SSH_DIGEST_SHA1)`.
const HASH_MAGIC: &str = "|1|";
const HASH_DELIM: char = '|';
const SALT_LEN: usize = 20;

type HmacSha1 = Hmac<Sha1>;

/// Generate a hashed host pattern for `hostname` using a fresh random salt.
///
/// Output format matches OpenSSH `host_hash()`: `|1|base64salt|base64hmac`.
/// Useful for writing entries with `HashKnownHosts yes`.
pub fn hash_host(hostname: &str) -> String {
    let mut salt = [0u8; SALT_LEN];
    rand::thread_rng().fill_bytes(&mut salt);
    hash_host_with_salt(hostname, &salt)
}

/// Generate a hashed host pattern with a caller-supplied salt (for tests
/// and deterministic output).
pub fn hash_host_with_salt(hostname: &str, salt: &[u8]) -> String {
    let mut mac = HmacSha1::new_from_slice(salt).expect("HMAC-SHA1 accepts any key length");
    mac.update(hostname.as_bytes());
    let result = mac.finalize().into_bytes();

    let b64 = base64::engine::general_purpose::STANDARD;
    format!(
        "{}{}{}{}",
        HASH_MAGIC,
        b64.encode(salt),
        HASH_DELIM,
        b64.encode(result)
    )
}

/// Verify whether a hashed pattern (`|1|…`) matches `hostname`.
///
/// Returns `false` for malformed patterns or on any decode error.
pub fn verify_hashed(pattern: &str, hostname: &str) -> bool {
    let Some(salt) = parse_hashed(pattern) else {
        return false;
    };
    // Re-encode over the same salt and compare the full canonical string,
    // mirroring OpenSSH's match_maybe_hashed() (strncmp of recomputed hash).
    // HMAC is case-sensitive — no lowercasing here.
    hash_host_with_salt(hostname, &salt) == pattern
}

/// Parse `|1|base64salt|base64hash` and return the decoded 20-byte salt.
///
/// The hash half is not decoded; verification works by recomputing the
/// full pattern from the salt and comparing strings (as OpenSSH does).
fn parse_hashed(pattern: &str) -> Option<Vec<u8>> {
    if !pattern.starts_with(HASH_MAGIC) {
        return None;
    }
    let rest = &pattern[HASH_MAGIC.len()..];
    let delim_pos = rest.find(HASH_DELIM)?;
    let b64salt = &rest[..delim_pos];
    let b64hash = &rest[delim_pos + 1..];
    if b64hash.is_empty() {
        return None;
    }

    let salt = base64::engine::general_purpose::STANDARD
        .decode(b64salt)
        .ok()?;
    if salt.len() != SALT_LEN {
        return None;
    }
    Some(salt)
}

#[cfg(test)]
mod tests {
    use super::*;

    // A real hashed entry generated by OpenSSH for host "sisyphus.example.com"
    // with a known salt, so the test is deterministic.
    // salt = 20 bytes of 0x01..0x14, hostname = "sisyphus.example.com"
    #[test]
    fn hash_and_verify_roundtrip() {
        let salt = [0x01u8; 20];
        let pattern = hash_host_with_salt("sisyphus.example.com", &salt);
        assert!(pattern.starts_with("|1|"));
        assert!(verify_hashed(&pattern, "sisyphus.example.com"));
        assert!(!verify_hashed(&pattern, "other.example.com"));
    }

    #[test]
    fn hash_host_format() {
        let pattern = hash_host("example.com");
        let parts: Vec<&str> = pattern.split('|').collect();
        // "" | "1" | salt | hash  (split on '|' yields 4 parts for |1|a|b)
        assert_eq!(parts.len(), 4, "pattern: {}", pattern);
        assert_eq!(parts[1], "1");
        // salt base64: 20 bytes -> 28 chars with padding
        assert_eq!(parts[2].len(), 28, "salt b64: {}", parts[2]);
        // hmac-sha1 base64: 20 bytes -> 28 chars with padding
        assert_eq!(parts[3].len(), 28, "hash b64: {}", parts[3]);
    }

    #[test]
    fn verify_rejects_malformed() {
        assert!(!verify_hashed("not-a-hash", "host"));
        assert!(!verify_hashed("|1|!!!bad!!!|!!!also-bad!!!", "host"));
        assert!(!verify_hashed("|1|c2FsdA==|aGFzaA==", "host")); // wrong salt len
        assert!(!verify_hashed("", "host"));
    }

    #[test]
    fn verify_is_case_sensitive() {
        let salt = [0x42u8; 20];
        let pattern = hash_host_with_salt("Host.Example.COM", &salt);
        assert!(verify_hashed(&pattern, "Host.Example.COM"));
        // HMAC is over exact bytes — case must match.
        assert!(!verify_hashed(&pattern, "host.example.com"));
    }
}
