//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "log_entry")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub repository_uuid: String,
    pub revision: Option<i64>,
    pub date: Option<i64>,
    pub author: Option<String>,
    pub message: Option<String>,
    pub has_children: bool,
    pub non_inheritable: bool,
    pub subtractive_merge: bool,
    #[sea_orm(has_many)]
    pub log_changed_path_entries: HasMany<super::log_changed_path_entry::Entity>,
    #[sea_orm(has_many)]
    pub properties: HasMany<super::property::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
