//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod log_changed_path_entry;
pub mod log_entry;
pub mod property;
pub mod workspace_history;
pub mod workspace_history_group;
