//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::log_changed_path_entry::Entity as LogChangedPathEntry;
pub use super::log_entry::Entity as LogEntry;
pub use super::property::Entity as Property;
pub use super::workspace_history::Entity as WorkspaceHistory;
pub use super::workspace_history_group::Entity as WorkspaceHistoryGroup;
