// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Depth } from './Depth'

export type AddOptions = {
  path: string
  depth: Depth
  force: boolean
  noIgnore: boolean
  noAutoProperties: boolean
  addParents: boolean
}
