// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlameEntry } from './BlameEntry'

export type BlameResult = { entries: Array<BlameEntry> }
