// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DifferenceFileOptions } from './DifferenceFileOptions'
import type { Revision } from './Revision'

export type BlameOptions = {
  path: string
  pegRevision: Revision
  startRevision: Revision
  endRevision: Revision
  differenceOptions: DifferenceFileOptions | null
  ignoreMimeType: boolean
  includeMergedRevisions: boolean
}
