// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BlameEntry = {
  lineNo: number
  revision: number | null
  author: string | null
  date: string | null
  line: string
  mergedRevision: number | null
  mergedAuthor: string | null
  mergedDate: string | null
  mergedPath: string | null
  localChange: boolean
}
