// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Revision } from './Revision'

export type CatOptions = {
  path: string
  pegRevision: Revision
  revision: Revision
  expandKeywords: boolean
  getProperties: boolean
}
