// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CatResult = { content: Uint8Array; properties: { [key in string]: string } | null }
