// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CheckSum =
  | { md5: Uint8Array }
  | { sha1: Uint8Array }
  | { fnv1a32: Uint8Array }
  | { fnv1a32x4: Uint8Array }
