// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Depth } from './Depth'
import type { Revision } from './Revision'

export type CheckoutOptions = {
  url: string
  path: string
  pegRevision: Revision
  revision: Revision
  depth: Depth
  ignoreExternals: boolean
  allowUnversionedObstructions: boolean
  storePristine: boolean | null
}
