// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CleanupOptions = {
  path: string
  breakLocks: boolean
  fixRecordedTimestamps: boolean
  clearDavCache: boolean
  vacuumPristines: boolean
  includeExternals: boolean
}
