// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientDifferenceSource } from './ClientDifferenceSource'
import type { Depth } from './Depth'

export type ClientDifferenceOptions = {
  options: Array<string> | null
  source: ClientDifferenceSource
  relateTo: string | null
  depth: Depth
  ignoreAncestry: boolean
  noAdded: boolean
  noDeleted: boolean
  showCopiesAsAdds: boolean
  ignoreContentType: boolean
  ignoreProperties: boolean
  propertiesOnly: boolean
  useGitFormat: boolean
  prettyPrintMergeInfo: boolean
  headerEncoding: string
  changelists: Array<string> | null
}
