// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Depth } from './Depth'

export type CommitOptions = {
  targets: Array<string>
  depth: Depth
  keepLocks: boolean
  keepChangelist: boolean
  commitAsOperations: boolean
  includeFileExternals: boolean
  includeDirExternals: boolean
  changelists: Array<string> | null
  revisionPropertyTable: { [key in string]: string } | null
  commitMessage: string
}
