// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CommitInfo = {
  revision: number
  date: string | null
  author: string | null
  postCommitErr: string | null
  reposRoot: string | null
}
