// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeKind } from './NodeKind'

export type CommitItem = {
  path: string | null
  kind: NodeKind
  url: string
  revision: number | null
  copyFromUrl: string | null
  copyFromRevision: number | null
  state: number
  incomingPropertyChanges: { [key in string]: string | null }
  outgoingPropertyChanges: { [key in string]: string | null }
  sessionRealPath: string | null
  moveFromAbsolutePath: string | null
}
