// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommitInfo } from './CommitInfo'
import type { CommitItem } from './CommitItem'

export type CommitResult = { items: Array<CommitItem>; info: CommitInfo | null }
