// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Conflict } from './Conflict'

export type ConflictWalkResult = { conflicts: Array<Conflict> }
