// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConflictOptionId } from './ConflictOptionId'
import type { WorkingCopyConflictAction } from './WorkingCopyConflictAction'
import type { WorkingCopyConflictReason } from './WorkingCopyConflictReason'
import type { WorkingCopyOperation } from './WorkingCopyOperation'

export type ConflictInfo = {
  localAbsolutePath: string
  operation: WorkingCopyOperation
  incomingChange: WorkingCopyConflictAction
  localChange: WorkingCopyConflictReason
  recommendedOptionId: ConflictOptionId
}
