// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConflictOptionId } from './ConflictOptionId'

export type ConflictOption = { id: ConflictOptionId; label: string; description: string }
