// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConflictInfo } from './ConflictInfo'
import type { ConflictPropertyValue } from './ConflictPropertyValue'
import type { NodeKind } from './NodeKind'

export type Conflict =
  | {
      text: {
        info: ConflictInfo
        baseAbsolutePath: string | null
        workingAbsolutePath: string | null
        incomingOldAbsolutePath: string | null
        incomingNewAbsolutePath: string | null
      }
    }
  | {
      property: {
        info: ConflictInfo
        properties: { [key in string]: ConflictPropertyValue }
        description: string | null
      }
    }
  | { tree: { info: ConflictInfo; victimNodeKind: NodeKind } }
