// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CopySourceItem } from './CopySourceItem'

export type CopyOptions = {
  sources: Array<CopySourceItem>
  destination: string
  copyAsChild: boolean
  makeParents: boolean
  ignoreExternals: boolean
  metadataOnly: boolean
  pinExternals: boolean
  revisionPropertyTable: { [key in string]: string } | null
  commitMessage: string
}
