// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeleteOptions = {
  path: Array<string>
  force: boolean
  keepLocal: boolean
  revisionPropertyTable: { [key in string]: string } | null
  commitMessage: string
}
