// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Depth = 'unknown' | 'exclude' | 'empty' | 'files' | 'immediates' | 'infinity'
