// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DifferenceFileOptions } from './DifferenceFileOptions'

export type DifferenceOptions = {
  original: Array<number>
  modified: Array<number>
  options: DifferenceFileOptions | null
}
