// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AprError } from './AprError'
import type { FrontendError } from './FrontendError'
import type { SubversionError } from './SubversionError'

export type Error =
  | { aprError: { source: AprError } }
  | { subversionError: { source: SubversionError } }
  | { invalidArgument: { detail: string } }
  | { iOError: { source: string } }
  | { invalidID: { source: string } }
  | { generalError: { detail: string } }
  | { runtimeError: { source: string } }
  | { whatever: { message: string } }
  | { jsonError: { source: string } }
  | { enumParseError: { source: string; detail: string } }
  | { tauriError: { source: FrontendError } }
  | { cacheBrokenError: { uuid: string } }
  | { databaseError: { source: string } }
  | { whichError: { source: string } }
  | { globError: { source: string } }
  | { unexpectedMessage: { detail: string } }
  | { messagePackError: { source: string } }
