// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Depth } from './Depth'
import type { NativeEOL } from './NativeEOL'
import type { Revision } from './Revision'

export type ExportOptions = {
  fromPathOrUrl: string
  toPath: string
  pegRevision: Revision
  revision: Revision
  override: boolean
  ignoreExternals: boolean
  ignoreKeywords: boolean
  depth: Depth
  nativeEol: NativeEOL
}
