// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LinkedLibrary } from './LinkedLibrary'
import type { LoadedLibrary } from './LoadedLibrary'
import type { Version } from './Version'

export type ExtendedVersion = {
  version: Version
  buildDate: string
  buildTime: string
  buildHost: string
  copyright: string
  runtimeHost: string
  runtimeOsName: string
  linkedLibraries: Array<LinkedLibrary>
  loadedLibraries: Array<LoadedLibrary>
}
