// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FrontendError =
  | { subversionError: { code: number; msg: string } }
  | { unexpectedError: { detail: string } }
  | { tauriError: { detail: string } }
