// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Depth } from './Depth'

export type ImportOptions = {
  path: string
  url: string
  depth: Depth
  noIgnore: boolean
  noAutoprops: boolean
  ignoreUnknownNodeTypes: boolean
  revisionPropertyTable: { [key in string]: string } | null
  commitMessage: string
}
