// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeKind } from './NodeKind'

export type ImportFilterEvent = {
  id: number
  path: string
  kind: NodeKind
  special: boolean
  fileSize: number | null
  mtime: number
}
