// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Lock } from './Lock'
import type { NodeKind } from './NodeKind'
import type { WorkingCopyInfo } from './WorkingCopyInfo'

export type InfoEntry = {
  url: string | null
  revision: number | null
  repositoryRootUrl: string | null
  repositoryUuid: string | null
  kind: NodeKind
  size: number | null
  lastChangedRevision: number | null
  lastChangedDate: number
  lastChangedAuthor: string | null
  lock: Lock | null
  workingCopyInfo: WorkingCopyInfo | null
}
