// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InfoEntry } from './InfoEntry'

export type InfoResult = { entries: { [key in string]: InfoEntry } }
