// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Depth } from './Depth'
import type { Revision } from './Revision'

export type InfoOptions = {
  path: string
  pegRevision: Revision
  revision: Revision
  depth: Depth
  fetchExcluded: boolean
  fetchActualOnly: boolean
  includeExternals: boolean
  changelists: Array<string> | null
}
