// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InitializeRepositoryOptions = {
  local: string
  remote: string
  backupDirectory: string | null
  commitMessage: string
  ignoreUnknownNodeTypes: boolean
  noIgnore: boolean
  noAutoprops: boolean
  filters: Array<string> | null
}
