// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Lock } from './Lock'
import type { NodeKind } from './NodeKind'

export type ListEntry = {
  path: string
  kind: NodeKind | null
  size: number | null
  hasProperties: boolean | null
  createdRevision: number | null
  time: number | null
  lastAuthor: string | null
  lock: Lock | null
  absolutePath: string
  externalParentUrl: string | null
  externalTarget: string | null
}
