// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Depth } from './Depth'
import type { Revision } from './Revision'

export type ListOptions = {
  path: string
  pegRevision: Revision
  revision: Revision
  patterns: Array<string> | null
  depth: Depth
  direntCreatedRevision: boolean
  direntHasProperties: boolean
  direntKind: boolean
  direntLastAuthor: boolean
  direntSize: boolean
  direntTime: boolean
  fetchLocks: boolean
  includeExternals: boolean
}
