// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Lock = {
  path: string | null
  token: string
  owner: string
  comment: string | null
  isDavComment: boolean
  creationDate: number
  expirationDate: number
}
