// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogChangedPathAction } from './LogChangedPathAction'
import type { NodeKind } from './NodeKind'

export type LogChangedPathEntry = {
  action: LogChangedPathAction
  copyFromPath: string | null
  copyFromRevision: number | null
  nodeKind: NodeKind
  textModified: boolean | null
  propsModified: boolean | null
}
