// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Revision } from './Revision'

export type LogCacheOptions = {
  repository: string
  pegRevision: Revision
  url: string
  path: string
  start: number | null
  limit: number
}
