// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogChangedPathEntry } from './LogChangedPathEntry'

export type LogEntry = {
  revision: number | null
  revisionProperties: { [key in string]: string } | null
  changedPathEntries: { [key in string]: LogChangedPathEntry }
  hasChildren: boolean
  nonInheritable: boolean
  subtractiveMerge: boolean
}
