// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Revision } from './Revision'
import type { RevisionRange } from './RevisionRange'

export type LogOptions = {
  targets: Array<string>
  pegRevision: Revision
  limit: number
  revisions: Array<RevisionRange>
  discoverChangedPaths: boolean
  strictNodeHistory: boolean
  includeMergedRevisions: boolean
  revisionsProperties: Array<string> | null
}
