// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Depth } from './Depth'
import type { MergeSource } from './MergeSource'

export type MergeOptions = {
  source: MergeSource
  target: string
  depth: Depth
  ignoreMergeInfo: boolean
  ignoreAncestry: boolean
  forceDelete: boolean
  recordOnly: boolean
  dryRun: boolean
  allowMixedRevision: boolean
  extraMergeOptions: Array<string> | null
}
