// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Revision } from './Revision'
import type { RevisionRange } from './RevisionRange'

export type MergeSource =
  | { target: { source1: string; revision1: Revision; source2: string; revision2: Revision } }
  | { peg: { source: string; pegRevision: Revision; rangesToMerge: Array<RevisionRange> | null } }
