// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MkdirOptions = {
  paths: Array<string>
  makeParents: boolean
  revisionPropertyTable: { [key in string]: string } | null
  commitMessage: string
}
