// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommitInfo } from './CommitInfo'

export type MoveResult = { commitInfo: CommitInfo | null }
