// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MoveOptions = {
  srcPaths: Array<string>
  destination: string
  moveAsChild: boolean
  makeParents: boolean
  allowMixedRevisions: boolean
  metadataOnly: boolean
  revisionPropertyTable: { [key in string]: string } | null
  commitMessage: string
}
