// This file was generated by `cargo test`. Do not edit this file manually.

export type NodePropertyName =
  | 'svn:mime-type'
  | 'svn:ignore'
  | 'svn:eol-style'
  | 'svn:keywords'
  | 'svn:executable'
  | 'svn:needs-lock'
  | 'svn:special'
  | 'svn:externals'
  | 'svn:mergeinfo'
  | 'svn:auto-props'
  | 'svn:global-ignores'
  | 'svn:text-time'
  | 'svn:owner'
  | 'svn:group'
  | 'svn:unix-mode'

export const nodePropertyNames: NodePropertyName[] = [
  'svn:mime-type',
  'svn:ignore',
  'svn:eol-style',
  'svn:keywords',
  'svn:executable',
  'svn:needs-lock',
  'svn:special',
  'svn:externals',
  'svn:mergeinfo',
  'svn:auto-props',
  'svn:global-ignores',
  'svn:text-time',
  'svn:owner',
  'svn:group',
  'svn:unix-mode',
]
