// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PatchOptions = {
  patchAbsolutePath: string
  wcAbsolutePath: string
  dryRun: boolean
  stripCount: number
  reverse: boolean
  ignoreWhitespace: boolean
  removeTempfiles: boolean
}
