// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InheritedProperty } from './InheritedProperty'

export type PropertyListEntry = {
  path: string
  properties: { [key in string]: string } | null
  inheritedProperties: Array<InheritedProperty> | null
}
