// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Depth } from './Depth'
import type { Revision } from './Revision'

export type PropertyGetOptions = {
  propertyName: string
  target: string
  pegRevision: Revision
  revision: Revision
  depth: Depth
  inherited: boolean
  actualRevision: boolean
  changelists: Array<string> | null
}
