// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InheritedProperty } from './InheritedProperty'

export type PropertyGetResult = {
  properties: { [key in string]: string }
  inheritedProperties: Array<InheritedProperty> | null
  actualRevision: number | null
}
