// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Depth } from './Depth'

export type PropertySetOptions =
  | {
      local: {
        name: string
        value: string | null
        targets: Array<string>
        depth: Depth
        skipChecks: boolean
        changelists: Array<string> | null
      }
    }
  | {
      remote: {
        name: string
        value: string | null
        url: string
        skipChecks: boolean
        baseRevisionForUrl: number
        revisionProperties: { [key in string]: string } | null
        commitMessage: string
      }
    }
