// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Proxy } from './Proxy'

export type Proxies = { http: Proxy | null; https: Proxy | null; socks: Proxy | null }
