// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Proxy = { host: string; port: number; username: string | null; password: string | null }
