// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FrontendError } from './FrontendError'

export type ReplyMessage = { success: Uint8Array } | { failure: FrontendError }
