// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Depth } from './Depth'

export type RevertOptions = {
  paths: Array<string>
  depth: Depth
  changelists: Array<string> | null
  clearChangelists: boolean
  metadataOnly: boolean
  addedKeepLocal: boolean
}
