// This file was generated by `cargo test`. Do not edit this file manually.

export type RevisionPropertyName =
  | 'svn:author'
  | 'svn:date'
  | 'svn:log'
  | 'svn:original-date'
  | 'svn:autoversioned'
  | 'svn:log'
  | 'svn:sync-from-url'
  | 'svn:sync-from-uuid'
  | 'svn:sync-last-merged-rev'
  | 'svn:sync-currently-copying'

export const revisionPropertyNames: RevisionPropertyName[] = [
  'svn:author',
  'svn:date',
  'svn:log',
  'svn:original-date',
  'svn:autoversioned',
  'svn:log',
  'svn:sync-from-url',
  'svn:sync-from-uuid',
  'svn:sync-last-merged-rev',
  'svn:sync-currently-copying',
]
