// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RevisionPropertyListResult = {
  properties: { [key in string]: string }
  revison: number
}
