// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Revision =
  | 'unspecified'
  | { number: number }
  | { date: number }
  | 'committed'
  | 'previous'
  | 'base'
  | 'working'
  | 'head'
