// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalePreference } from './LocalePreference'
import type { ProxyType } from './ProxyType'
import type { ThemeMode } from './ThemeMode'

/**
 * 设置弹窗里的全部设置项。字段缺失时取 `Default`，方便手工编辑或版本演进。
 */
export type Settings = {
  theme: ThemeMode
  locale: LocalePreference
  defaultUsername: string
  defaultPassword: string
  proxyEnabled: boolean
  proxyType: ProxyType
  proxyHost: string
  proxyPort: number | null
  proxyUsername: string
  proxyPassword: string
}
