// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SSHAuthetication =
  | { password: { password: string; username: string } }
  | { publicKey: { file: string; username: string; passphrase: string | null } }
  | { keyboardInteractive: { username: string } }
