// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SslServerCertInfo = {
  hostname: string | null
  fingerprint: string
  validFrom: string
  validUntil: string
  issuer: string
  asciiCert: string
}
