// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Depth } from './Depth'
import type { Lock } from './Lock'
import type { NodeKind } from './NodeKind'
import type { WorkingCopyStatus } from './WorkingCopyStatus'

export type StatusEntry = {
  path: string
  nodeKind: NodeKind
  localAbsolutePath: string
  fileSize: number | null
  versioned: boolean
  conflicted: boolean
  nodeStatus: WorkingCopyStatus
  textStatus: WorkingCopyStatus
  propertyStatus: WorkingCopyStatus
  wcIsLocked: boolean
  copied: boolean
  repositoryRootUrl: string | null
  repositoryUuid: string | null
  repositoryRelpath: string | null
  revision: number | null
  lastChangedRevision: number | null
  lastChangedDate: number
  lastChangedAuthor: string | null
  switched: boolean
  fileExternal: boolean
  lock: Lock | null
  changelist: string | null
  depth: Depth
  outOfDateKind: NodeKind
  repositoryNodeStatus: WorkingCopyStatus
  repositoryTextStatus: WorkingCopyStatus
  repositoryPropertyStatus: WorkingCopyStatus
  repositoryLock: Lock | null
  outOfDateChangedRevision: number | null
  outOfDateChangedDate: number | null
  outOfDateChangedAuthor: string | null
  movedFromAbsolutePath: string | null
  movedToAbsolutePath: string | null
}
