// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Depth } from './Depth'
import type { Revision } from './Revision'

export type StatusOptions = {
  path: string
  revision: Revision
  depth: Depth
  getAll: boolean
  checkOutOfDate: boolean
  checkWorkingCopy: boolean
  noIgnore: boolean
  ignoreExternals: boolean
  depthAsSticky: boolean
  changelist: Array<string> | null
}
