// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubversionErrorCode } from './SubversionErrorCode'

export type SubversionErrorInfo = {
  status: number
  code: SubversionErrorCode
  msg: string
  file: string
  line: number
}
