// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubversionErrorCode } from './SubversionErrorCode'
import type { SubversionErrorInfo } from './SubversionErrorInfo'

export type SubversionError = {
  msg: string
  status: number
  code: SubversionErrorCode
  info: Array<SubversionErrorInfo>
}
