// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SslServerCertInfo } from './SslServerCertInfo'
import type { WorkingCopyConflictDescription } from './WorkingCopyConflictDescription'
import type { WorkingCopyNotify } from './WorkingCopyNotify'

export type SubversionEvent =
  | { savePasswordAsPlainText: { id: number; realm: string } }
  | { workingCopyNotify: { notify: WorkingCopyNotify } }
  | {
      sslServerTrustPrompt: {
        id: number
        realm: string
        failures: number
        info: SslServerCertInfo
        maySave: boolean
      }
    }
  | { progressNotify: { pos: number; total: number } }
  | {
      authenticate: {
        id: number
        realm: string
        username: string
        maySave: boolean
        needPassword: boolean
      }
    }
  | { conflict: { id: number; description: WorkingCopyConflictDescription } }
  | { sslClientCertificate: { id: number; realm: string; maySave: boolean } }
