// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SubversionSSHEvent =
  | {
      verifyIpChanged: {
        id: number
        host: string
        ip: string
        keyType: string
        keyData: Array<number>
        fingerprint: string
      }
    }
  | {
      verifyNewHostKey: {
        id: number
        host: string
        ip: string | null
        keyType: string
        keyData: Array<number>
        fingerprint: string
      }
    }
  | {
      keyboardInteractive: {
        id: number
        name: string
        instruction: string
        prompts: Array<[string, boolean]>
      }
    }
  | {
      authenticate: {
        id: number
        password: boolean
        publicKey: boolean
        keyboardInteractive: boolean
        username: string | null
      }
    }
  | { passphrase: { id: number; path: string; username: string | null; wrong: boolean } }
