// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Depth } from './Depth'
import type { Revision } from './Revision'

export type SwitchOptions = {
  path: string
  url: string
  pegRevision: Revision
  revision: Revision
  depth: Depth
  depthIsSticky: boolean
  ignoreExternals: boolean
  allowUnversionedObstructions: boolean
  ignoreAncestry: boolean
}
