// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Depth } from './Depth'
import type { Revision } from './Revision'

export type UpdateOptions = {
  paths: Array<string>
  revision: Revision
  depth: Depth
  depthIsSticky: boolean
  ignoreExternals: boolean
  allowUnverObstructions: boolean
  addsAsModification: boolean
  makeParents: boolean
}
