// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Version = { major: number; minor: number; patch: number; tag: string | null }
