// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkingCopyConflictChoice } from './WorkingCopyConflictChoice'

export type WorkingCopyConflictResult = {
  choice: WorkingCopyConflictChoice
  mergedFile: string | null
  saveMerged: boolean
  mergedValue: string | null
}
