// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeKind } from './NodeKind'

export type WorkingCopyConflictVersion = {
  repositoryUrl: string
  pegRevision: number
  pathInRepository: string
  nodeKind: NodeKind
  repositoryUuid: string | null
}
