// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkingCopyRevisionStatus = {
  minRevision: number
  maxRevision: number
  switched: boolean
  modified: boolean
  sparseCheckout: boolean
}
