// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeKind } from './NodeKind'
import type { WorkingCopyConflictAction } from './WorkingCopyConflictAction'
import type { WorkingCopyConflictKind } from './WorkingCopyConflictKind'
import type { WorkingCopyConflictReason } from './WorkingCopyConflictReason'
import type { WorkingCopyConflictVersion } from './WorkingCopyConflictVersion'
import type { WorkingCopyOperation } from './WorkingCopyOperation'

export type WorkingCopyConflictDescription = {
  localAbsolutePath: string
  nodeKind: NodeKind
  kind: WorkingCopyConflictKind
  propertyName: string | null
  isBinary: boolean
  mimeType: string | null
  action: WorkingCopyConflictAction
  reason: WorkingCopyConflictReason
  baseAbsolutePath: string | null
  theirAbsolutePath: string | null
  myAbsolutePath: string | null
  mergedFile: string | null
  operation: WorkingCopyOperation
  sourceLeftVersion: WorkingCopyConflictVersion | null
  sourceRightVersion: WorkingCopyConflictVersion | null
  propertyRejectAbsolutePath: string | null
  propertyValueBase: string | null
  propertyValueWorking: string | null
  propertyValueIncomingOld: string | null
  propertyValueIncomingNew: string | null
}
