// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkingCopyStatus =
  | 'none'
  | 'unversioned'
  | 'normal'
  | 'added'
  | 'missing'
  | 'deleted'
  | 'replaced'
  | 'modified'
  | 'merged'
  | 'conflicted'
  | 'ignored'
  | 'obstructed'
  | 'external'
  | 'incomplete'
