// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspaceItem =
  | {
      workingCopy: {
        workingCopyRoot: string
        workingCopyPath: string
        repositoryRootUrl: string | null
        lastUsedTime: number | null
        checkout: number | null
        order: string
        star: boolean
        identity: string
        remark: string | null
        name: string
      }
    }
  | {
      repository: {
        repositoryRootUrl: string
        repositoryUuid: string
        lastUsedTime: number | null
        order: string
        star: boolean
        identity: string
        remark: string | null
        name: string
      }
    }
