// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkingCopyNotifyState =
  | 'Inapplicable'
  | 'Unknown'
  | 'Unchanged'
  | 'Missing'
  | 'Obstructed'
  | 'Changed'
  | 'Merged'
  | 'Conflicted'
  | 'SourceMissing'
