// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckSum } from './CheckSum'
import type { Depth } from './Depth'
import type { WorkingCopySchedule } from './WorkingCopySchedule'

export type WorkingCopyInfo = {
  schedule: WorkingCopySchedule
  copyFromRevision: number | null
  checkSum: CheckSum | null
  changelist: string | null
  depth: Depth
  recordedSize: number | null
  recordedTime: number
  workingCopyAbsolutePath: string
  movedFromAbsolutePath: string | null
  movedToAbsolutePath: string | null
  workingCopyFormat: number
  storePristine: boolean
}
