// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkingCopyConflictChoice =
  | 'undefined'
  | 'postpone'
  | 'base'
  | 'theirsFull'
  | 'mineFull'
  | 'theirsConflict'
  | 'mineConflict'
  | 'merged'
  | 'unspecified'
