// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Lock } from './Lock'
import type { MergeRange } from './MergeRange'
import type { NodeKind } from './NodeKind'
import type { SubversionError } from './SubversionError'
import type { WorkingCopyNotifyAction } from './WorkingCopyNotifyAction'
import type { WorkingCopyNotifyLockState } from './WorkingCopyNotifyLockState'
import type { WorkingCopyNotifyState } from './WorkingCopyNotifyState'

export type WorkingCopyNotify = {
  path: string
  action: WorkingCopyNotifyAction
  kind: NodeKind
  mimeType: string | null
  lock: Lock | null
  err: SubversionError | null
  contentState: WorkingCopyNotifyState
  propertyState: WorkingCopyNotifyState
  lockState: WorkingCopyNotifyLockState
  revision: number | null
  changelistName: string | null
  mergeRange: MergeRange | null
  url: string | null
  pathPrefix: string | null
  propertyName: string | null
  revisionProperties: { [key in string]: string }
  oldRevision: number | null
  hunkOriginalStart: number
  hunkOriginalLength: number
  hunkModifiedStart: number
  hunkModifiedLength: number
  hunkMatchedLine: number
  hunkFuzz: number
}
