#[cfg(test)]
mod tests {
    use super::super::ffi;
    use serde::{Deserialize, Serialize};
    use std::io::Write;
    use strum::IntoEnumIterator;

    const fn cbytes_as_str(bytes: &[u8]) -> &str {
        let value = match std::ffi::CStr::from_bytes_with_nul(bytes) {
            Ok(v) => v,
            Err(_) => panic!("Invalid string"),
        };
        match value.to_str() {
            Ok(v) => v,
            Err(_) => panic!("Invalid string"),
        }
    }

    fn lowercase_first(s: &str) -> String {
        let mut chars = s.chars();

        match chars.next() {
            None => String::new(),
            Some(first) => first.to_lowercase().collect::<String>() + chars.as_str(),
        }
    }

    #[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, strum::EnumIter)]
    pub enum RevisionPropertyName {
        Author,
        Date,
        Log,
        OriginalDate,
        Autoversioned,
        Lock,
        FromUrl,
        FromUuid,
        LastMergedRevision,
        CurrentCopying,
    }

    impl RevisionPropertyName {
        fn name(&self) -> String {
            self.as_str().to_string()
        }
    }

    impl RevisionPropertyName {
        fn as_str(&self) -> &'static str {
            match self {
                RevisionPropertyName::Author => cbytes_as_str(ffi::SVN_PROP_REVISION_AUTHOR),
                RevisionPropertyName::Date => cbytes_as_str(ffi::SVN_PROP_REVISION_DATE),
                RevisionPropertyName::Log => cbytes_as_str(ffi::SVN_PROP_REVISION_LOG),
                RevisionPropertyName::OriginalDate => {
                    cbytes_as_str(ffi::SVN_PROP_REVISION_ORIG_DATE)
                }
                RevisionPropertyName::Autoversioned => {
                    cbytes_as_str(ffi::SVN_PROP_REVISION_AUTOVERSIONED)
                }
                RevisionPropertyName::Lock => cbytes_as_str(ffi::SVN_PROP_REVISION_LOG),
                RevisionPropertyName::FromUrl => cbytes_as_str(ffi::SVNSYNC_PROP_FROM_URL),
                RevisionPropertyName::FromUuid => cbytes_as_str(ffi::SVNSYNC_PROP_FROM_UUID),
                RevisionPropertyName::LastMergedRevision => {
                    cbytes_as_str(ffi::SVNSYNC_PROP_LAST_MERGED_REV)
                }
                RevisionPropertyName::CurrentCopying => {
                    cbytes_as_str(ffi::SVNSYNC_PROP_CURRENTLY_COPYING)
                }
            }
        }
    }

    #[derive(Debug, Clone, Copy, PartialEq, Eq, strum::EnumIter)]
    enum NodePropertyName {
        MimeType,
        Ignore,
        EolStyle,
        Keywords,
        Exeucable,
        NeedsLock,
        Special,
        Externals,
        MergeInfo,
        AutoProperties,
        GlobalIgnores,
        TextTime,
        Owner,
        Group,
        UnixMode,
    }

    impl NodePropertyName {
        fn name(&self) -> String {
            self.as_str().to_string()
        }
    }

    impl NodePropertyName {
        fn as_str(&self) -> &'static str {
            match self {
                NodePropertyName::MimeType => cbytes_as_str(ffi::SVN_PROP_MIME_TYPE),
                NodePropertyName::Ignore => cbytes_as_str(ffi::SVN_PROP_IGNORE),
                NodePropertyName::EolStyle => cbytes_as_str(ffi::SVN_PROP_EOL_STYLE),
                NodePropertyName::Keywords => cbytes_as_str(ffi::SVN_PROP_KEYWORDS),
                NodePropertyName::Exeucable => cbytes_as_str(ffi::SVN_PROP_EXECUTABLE),
                NodePropertyName::NeedsLock => cbytes_as_str(ffi::SVN_PROP_NEEDS_LOCK),
                NodePropertyName::Special => cbytes_as_str(ffi::SVN_PROP_SPECIAL),
                NodePropertyName::Externals => cbytes_as_str(ffi::SVN_PROP_EXTERNALS),
                NodePropertyName::MergeInfo => cbytes_as_str(ffi::SVN_PROP_MERGEINFO),
                NodePropertyName::AutoProperties => {
                    cbytes_as_str(ffi::SVN_PROP_INHERITABLE_AUTO_PROPS)
                }
                NodePropertyName::GlobalIgnores => cbytes_as_str(ffi::SVN_PROP_INHERITABLE_IGNORES),
                NodePropertyName::TextTime => cbytes_as_str(ffi::SVN_PROP_TEXT_TIME),
                NodePropertyName::Owner => cbytes_as_str(ffi::SVN_PROP_OWNER),
                NodePropertyName::Group => cbytes_as_str(ffi::SVN_PROP_GROUP),
                NodePropertyName::UnixMode => cbytes_as_str(ffi::SVN_PROP_UNIX_MODE),
            }
        }
    }
    #[test]
    fn export_revision_property_name_ts() {
        let variants: Vec<String> = RevisionPropertyName::iter()
            .map(|v| format!("\"{}\"", v.name()))
            .collect();

        let type_name = "RevisionPropertyName";

        let ts_content = format!(
            concat!(
                "// This file was generated by `cargo test`. Do not edit this file manually.\n\n",
                "export type {} = {};\n\n",
                "export const {}: {}[] = [{}]"
            ),
            type_name,
            variants.join(" | "),
            format!("{}s", lowercase_first(type_name)),
            type_name,
            variants.join(", ")
        );

        let out_dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../src/bindings");
        let out_path = out_dir.join("RevisionPropertyName.ts");

        let mut file = std::fs::File::create(&out_path).expect("Failed to create file");
        file.write_all(ts_content.as_bytes())
            .expect("Failed to write file");

        println!("Generated: {}", out_path.display());
    }

    #[test]
    fn export_node_property_name_ts() {
        let variants: Vec<String> = NodePropertyName::iter()
            .map(|v| format!("\"{}\"", v.name()))
            .collect();

        let type_name = "NodePropertyName";

        let ts_content = format!(
            concat!(
                "// This file was generated by `cargo test`. Do not edit this file manually.\n\n",
                "export type {} = {};\n\n",
                "export const {}: {}[] = [{}];\n\n"
            ),
            type_name,
            variants.join(" | "),
            format!("{}s", lowercase_first(type_name)),
            type_name,
            variants.join(", ")
        );

        let out_dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../src/bindings");
        let out_path = out_dir.join("NodePropertyName.ts");

        let mut file = std::fs::File::create(&out_path).expect("Failed to create file");
        file.write_all(ts_content.as_bytes())
            .expect("Failed to write file");

        println!("Generated: {}", out_path.display());
    }
}
