//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "property")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: String,
    pub value: String,
    pub log_entry_id: Option<i64>,
    #[sea_orm(
        belongs_to,
        from = "log_entry_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub log_entry: HasOne<super::log_entry::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
