//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "workspace_history")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub uuid: String,
    pub last_used_time: Option<i64>,
    pub star: bool,
    pub remark: Option<String>,
    pub repository_root_url: Option<String>,
    pub working_copy_path: Option<String>,
    pub working_copy_root: Option<String>,
    pub checkout: bool,
    pub repository_uuid: Option<String>,
    pub kind: String,
}

impl ActiveModelBehavior for ActiveModel {}
